# Name: Tushar Shrivastav
# Date: Friday 2:15
# Title: Lab8
# Description: Makefile for executing code, called by bash script

all: fifo.c lru.c sec_chance.c
	gcc -o lru lru.c
	gcc -o fifo fifo.c
	gcc -o sec_chance sec_chance.c

clean:
	rm -f *.out lru fifo sec_chance

